package:
  name: libxt-cos7-ppc64le
  version: 1.1.5
source:
  - folder: binary
    sha256: 6634b8720eb95a0b39779131bdeae73225c67a967c4f2a8f05977e9ba28c7bad
    url: http://mirror.centos.org/altarch/7/os/ppc64le/Packages/libXt-1.1.5-3.el7.ppc64le.rpm
  - folder: source
    url: http://vault.centos.org/7.6.1810/os/Source/SPackages/libXt-1.1.5-3.el7.src.rpm
    sha256: 2ed20bbe0683467fa8f66bc028a282c93569525d95ff38295b9d22af560b102a

build:
  number: 0
  noarch: generic
requirements:
  run:
      - libx11-cos7-ppc64le >=1.6.5

about:
  description: 'X.org X11 libXt runtime library'
  home: http://www.x.org
  license: MIT
  license_family: MIT
  summary: (CDT) X.org X11 libXt runtime library
extra:
  copy_test_source_files: true
  final: true
