package:
  name: libxt-cos7-ppc64le
  version: 1.1.5

source:
  - url: http://mirror.centos.org/altarch/7.6.1810/os/ppc64le/Packages/libXt-1.1.5-3.el7.ppc64le.rpm
    sha256: 6634b8720eb95a0b39779131bdeae73225c67a967c4f2a8f05977e9ba28c7bad
    folder: binary

build:
  number: 0
  noarch: generic
  missing_dso_whitelist:
    - '*'

test:
  commands:
    - test -d "${PREFIX}/ppc64le-conda_cos7-linux-gnu/sysroot"
  requires:
    - zlib

about:
  home:
  license: LGPLv2/GPLv2
  license_family: GPL2
  summary:
  description: |
