{% set version = "2.10" %}

package:
  name: tktable
  version: {{ version }}

source:
  url: http://downloads.sourceforge.net/project/tktable/tktable/{{ version }}/Tktable{{ version }}.tar.gz
  sha256: c335117fa1be45fe4d3032e96fd4b4641fff6a4f8467878608dabed11198a4cb

build:
  skip: True  # [win]
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
    - {{ cdt('libx11-devel') }}          # [linux]
    - libxcb
    - xorg-libxau
    - make
  host:
    - tk
  run:
    - tk

test:
  commands:
          #    - echo "if {[catch {package require -exact Tktable {{ version }}; exit 0}]} {exit 1}" | xvfb-run tclsh  # [linux]
    - echo "if {[catch {package require -exact Tktable {{ version }}; exit 0}]} {exit 1}" | tclsh  # [osx]

about:
  home: http://www.tcl.tk/
  license: Tcl/Tk
  license_family: BSD
  license_file: license.txt
  summary: Tktable is a 2D editable table widget
  doc_url: https://core.tcl.tk/jenglish/gutter/packages/tktable.html

extra:
  recipe-maintainers:
    - fhoehle
