{% set name = "ibm_db_sa" %}
{% set version = "0.3.5" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/ibmdb/python-ibmdbsa.git
  git_rev: 0b85c013e4a7effc7c57bd752ee570959e23bb6a


build:
  number: 0

requirements:
  host:
    - ibm_db >=2.0.0
    - pip
    - python
    - setuptools
    - sqlalchemy >=0.7.3
  run:
    - ibm_db >=2.0.0
    - python
    - setuptools
    - sqlalchemy >=0.7.3

test:
  imports:
    - ibm_db_sa
  requires:
    - nose >=0.11

about:
  home: "http://pypi.python.org/pypi/ibm_db_sa/"
  license: Apache Software
  license_family: APACHE
  license_file: 
  summary: "SQLAlchemy support for IBM Data Servers"
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - jayfurmanek
