{% set version = '0.1-45' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-slam
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/slam_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/slam/slam_{{ version }}.tar.gz
  sha256: 84ab3919c7dbac41d97d076787feacfd6861f669aa2842879dffb46ed4467277

build:
  merge_build_host: True  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
  run:
    - r-base
    - {{native}}gcc-libs         # [win]

test:
  commands:
    - $R -e "library('slam')"           # [not win]
    - "\"%R%\" -e \"library('slam')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=slam
  license: GPL-2
  summary: Data structures and algorithms for sparse arrays and matrices, based on index arrays
    and simple triplet representations, respectively.
  license_family: GPL2
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - croth1
    - conda-forge/r

# Package: slam
# Version: 0.1-45
# Title: Sparse Lightweight Arrays and Matrices
# Authors@R: c(person("Kurt", "Hornik", role = c("aut", "cre"), email = "Kurt.Hornik@R-project.org", comment = c(ORCID = "0000-0003-4198-9911")), person("David", "Meyer", role = "aut"), person("Christian", "Buchta", role = "aut"))
# Description: Data structures and algorithms for sparse arrays and matrices, based on index arrays and simple triplet representations, respectively.
# Depends: R (>= 3.4.0)
# Imports: stats
# Enhances: Matrix, SparseM, spam
# License: GPL-2
# NeedsCompilation: yes
# Packaged: 2019-02-26 10:47:45 UTC; hornik
# Author: Kurt Hornik [aut, cre] (<https://orcid.org/0000-0003-4198-9911>), David Meyer [aut], Christian Buchta [aut]
# Maintainer: Kurt Hornik <Kurt.Hornik@R-project.org>
# Repository: CRAN
# Date/Publication: 2019-02-26 11:23:12 UTC
