{% set version = "1.2.0" %}
{% set name = "tensorflow-datasets" %}
{% set sha256 = "a3f2c0f9b553cf01f03bc42a84649c93c2acf668e5e82c0e4ce163692cf274d4" %}
{% set tensorflow_version = "1.14.0" %}

# This is the recipe for tensorflow-datasets
package:
   name: {{ name }}
   version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  #git_url: https://github.com/tensorflow/datasets.git
  #git_rev: v1.2.0 
  sha256: {{ sha256 }}

build:
  number: 0 
  noarch: python

requirements:
  host:
     - python
  build:
     - git >=2.2 
  run:
   # conda build requirements
     - python
     - absl-py
     - attrs
     - dill
     - future
     - numpy
     - promise
     - protobuf >=3.6.1
     - psutil
     - requests >=2.19.0
     - six
     - tensorflow-metadata
     - termcolor
     - tqdm
     - wrapt
     - tensorflow-base >={{ tensorflow_version }}
     - mock              # [py2k]
     - bz2file           # [py2k]
     - functools32       # [py2k]
     - futures           # [py2k]

about:
  home: https://github.com/tensorflow/datasets
  license: Apache License 2.0
  summary: "A collection of datasets ready to use with TensorFlow"
  description: |
      tensorflow-datasets is a library of public datasets ready to use with
      TensorFlow. Each dataset definition contains the logic necessary to 
      download and prepare the dataset, as well as to read it into a model using the
      `tf.data.Dataset` API.
      Usage outside of TensorFlow is also supported.
  dev_url: https://github.com/tensorflow/datasets.git
  doc_url: https://github.com/tensorflow/datasets.git 
