{% set version = '0.6-4' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rglpk
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/Rglpk_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/Rglpk/Rglpk_{{ version }}.tar.gz
  sha256: a28dbc3130b9618d6ed2ef718d2c55df8ed8c44a47161097c53fe15fa3bfbfa6

build:
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}sed               # [win]
    - {{posix}}grep              # [win]
    - {{posix}}autoconf
    - {{posix}}automake          # [not win]
    - {{posix}}automake-wrapper  # [win]
    - {{posix}}pkg-config
    - {{posix}}make
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-slam >=0.1_9
    - glpk
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-slam >=0.1_9
    - glpk

test:
  commands:
    - $R -e "library('Rglpk')"           # [not win]
    - "\"%R%\" -e \"library('Rglpk')\""  # [win]

about:
  home: http://R-Forge.R-project.org/projects/rglp/, http://www.gnu.org/software/glpk/
  license: GPL-2 | GPL-3
  summary: R interface to the GNU Linear Programming Kit. 'GLPK' is open source software for
    solving large-scale linear programming (LP), mixed integer linear programming ('MILP')
    and other related problems.
  license_family: GPL3

extra:
  recipe-maintainers:
    - jayfurmanek

# Package: Rglpk
# Version: 0.6-4
# Title: R/GNU Linear Programming Kit Interface
# Description: R interface to the GNU Linear Programming Kit. 'GLPK' is open source software for solving large-scale linear programming (LP), mixed integer linear programming ('MILP') and other related problems.
# Authors@R: c(person("Stefan", "Theussl", role = c("aut", "cre"), email = "Stefan.Theussl@R-project.org"), person("Kurt", "Hornik", role = "aut"), person("Christian", "Buchta", role = "ctb"), person("Florian", "Schwendinger", role = "ctb"), person("Heinrich", "Schuchardt", role = "ctb"))
# Depends: slam (>= 0.1-9)
# SystemRequirements: GLPK library package (e.g., libglpk-dev on Debian/Ubuntu)
# License: GPL-2 | GPL-3
# URL: http://R-Forge.R-project.org/projects/rglp/, http://www.gnu.org/software/glpk/
# NeedsCompilation: yes
# Packaged: 2019-02-08 18:08:20 UTC; theussl
# Author: Stefan Theussl [aut, cre], Kurt Hornik [aut], Christian Buchta [ctb], Florian Schwendinger [ctb], Heinrich Schuchardt [ctb]
# Maintainer: Stefan Theussl <Stefan.Theussl@R-project.org>
# Repository: CRAN
# Date/Publication: 2019-02-09 15:33:16 UTC
