{% set name = "gym" %}
{% set version = "0.15.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/openai/gym.git
  git_rev: {{ version }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  noarch: python

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - six
    - scipy
    - numpy >=1.10.4
    - pyglet>=1.2.0,<=1.3.2
    - cloudpickle~=1.2.0
    - enum34~=1.1.6     #[py27] 
    - py-opencv

test:
  imports:
    - gym
    - gym.envs
    - gym.envs.algorithmic
    - gym.envs.algorithmic.tests
    - gym.envs.box2d
    - gym.wrappers
    - gym.wrappers.monitoring
    - gym.wrappers.monitoring.tests
    - gym.wrappers.tests
  requires:
    - mock
    - pytest

about:
  home: https://github.com/openai/gym
  license: MIT
  license_family: MIT
  license_file: 'LICENSE'
  summary: 'A toolkit for developing and comparing reinforcement learning algorithms'
  description: |
      OpenAI Gym is a toolkit for developing and comparing reinforcement learning
      algorithms. This is the gym open-source library, which gives you access to
      a standardized set of environments.
  doc_url: https://github.com/openai/gym
  dev_url: https://github.com/openai/gym

