{% set name = "pytext-nlp" %}
{% set version = "0.3.1" %}

package:
  name: "{{ name }}"
  version: "{{ version }}"

source:
  - url: https://github.com/facebookresearch/pytext/archive/{{ version }}.tar.gz
    sha256: e8c7cbdd026a27e9089df07bda362379a04143d7b97336567b17c3a3c67de8f1 
    patches:
      - 0001-setup-requirements.patch
      - 0002-set-locale.patch
      - 0005-set-generated-model-path.patch 
      - 0007-expandpath.patch
      - 0008-Fix-docstring-for-export.patch

build:
  number: 0 

requirements:
  host:
    - python
    - setuptools=41*
    - pytorch=1.3.1

  run:
    - python
    - click=7.0
    - future=0.17.1
    - hypothesis=3.59.1
    - numpy=1.17.*
    - scipy=1.3.*
    - onnx=1.6.0
    - joblib=0.13.2 
    - requests=2.22
    - pandas=0.24.2
    - regex=2019.11.1
    - python-dateutil==2.8.0
    - torchtext=0.4.0
    - typing-extensions
    - pytorch=1.3.1
    - tensorboard=2.1.* 
    - absl-py=0.8.1 
    - fairseq
    - sentencepiece
    - pytorch-pretrained-bert

about:
  home: https://github.com/facebookresearch/pytext 
  license: BSD License
  license_file: LICENSE
  summary: A natural language modeling framework based on PyTorch 
