export CONDA_BACKUP_JAVA_HOME="${JAVA_HOME}"
export JAVA_HOME="${CONDA_PREFIX}"
export CONDA_BACKUP_JAVA_LD_LIBRARY_PATH="${JAVA_LD_LIBRARY_PATH}"

export JAVA_LD_LIBRARY_PATH="${JAVA_HOME}"/jre/lib/server
