{% set name = "ray" %}
{% set version = "0.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/ray-project/ray.git
  git_rev: ray-{{ version }}
  patches:
    - redis-bazel-build.patch
    - 0001-Added-a-patch-to-fix-boost-compilation-on-ppc64le.patch
    - 0002-Arrow-Fixes-PPC.patch

build:
  number: 0
  entry_points:
    - ray=ray.scripts.scripts:main
    - rllib=ray.rllib.scripts:cli [rllib]
    - tune=ray.tune.scripts:cli

requirements:
  host:
    - python
    - cython>=0.29
  build:
    - python
    - cython>=0.29
    - bazel==1.0.0
    - git
    - cmake
    - make
    - setuptools
    - unzip
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  run:
    - python
    - numpy >=1.16
    - filelock
    - jsonschema
    - funcsigs
    - click
    - colorama
    - packaging
    - pytest
    - pyyaml
    - redis-py>=3.3.2
    - six>=1.0.0
    - faulthandler   #[py<33] 
    - protobuf >=3.8.0
    - cloudpickle
    - pyarrow

test:
  imports:
    - ray

about:
  home: https://github.com/ray-project/ray
  license: Apache-2.0
  license_family: Apache
  summary: 'Ray is a flexible, high-performance distributed execution framework.'
  description: |
    Ray is a Python-based distributed execution engine.
    The same code can be run on a single machine to achieve efficient multiprocessing,
    and it can be used on a cluster for large computations.
  doc_url: http://ray.readthedocs.io/en/latest/?badge=latest
  dev_url: https://github.com/ray-project/ray
