{% set name = "ray" %}
{% set version = "0.7.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/ray-project/ray.git
  git_rev: ray-{{ version }}
  patches:
    - redis-bazel-build.patch
    
build:
  noarch: python
  number: 0

requirements:
  host:
    - python
    - cython==0.29.0
    - openssl
    - bazel
    - arrow
    - pip
    - pyarrow
    - git
    - cmake
    - make
    - setuptools
    - protobuf==3.8.0
    - redis
    - redis-py
    - pyyaml
    - pytest
    - colorama
    - click
    - funcsigs
    - jsonschema
    - filelock
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  run:
    - numpy
    - colorama
    - protobuf
    - redis
    - redis-py
    - funcsigs
    - jsonschema
    - yaml
    - pyyaml
    - psutil
    - pyarrow

test:
  imports:
    - ray

about:
  home: https://github.com/ray-project/ray
  license: Apache-2.0
  license_family: Apache
  summary: 'Ray is a flexible, high-performance distributed execution framework.'
  description: |
    Ray is a Python-based distributed execution engine.
    The same code can be run on a single machine to achieve efficient multiprocessing,
    and it can be used on a cluster for large computations.
  doc_url: http://ray.readthedocs.io/en/latest/?badge=latest
  dev_url: https://github.com/ray-project/ray
