{% set version="1.4.3" %}

package:
  name: sacrebleu  
  version: {{ version }}

source:
  git_url: https://github.com/mjpost/sacreBLEU.git
  git_tag: v{{ version }}

build:
  number: 0
  noarch: python
  skip: True  # [win and py2k]
  script: python setup.py install

requirements:
  host:
    - python >=3
    - portalocker
    - typing

  run:
    - python >=3
    - portalocker
    - typing

test:
  imports:
    - sacrebleu
 
about:
  home: https://github.com/mjpost/sacreBLEU/ 
  license: Apache License 2.0
  license_file: LICENSE.txt
  summary: Reference BLEU implementation
  description: Auto-downloads test sets and reports a version string to facilitate cross-lab comparisons
