{% set name = "pyglet" %}
{% set version = "1.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/pyglet/pyglet.git
  git_rev: pyglet-1.3-maintenance

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - future

test:
  requires:
    - libglu
  imports:
    - pyglet
    - pyglet.app
    - pyglet.canvas
    - pyglet.extlibs
about:
  home: https://github.com/pyglet/pyglet
  license: BSD
  license_family: BSD
  license_file: 'LICENSE'
  summary: 'An interface for developing games and other visually-rich applications'
  description: |
      pyglet provides an object-oriented programming interface for developing games
      and other visually-rich applications for Windows, Mac OS X and Linux.
  doc_url: https://github.com/pyglet/pyglet
  dev_url: https://github.com/pyglet/pyglet

