{% set version = '1.2.4' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-minqa
  version: {{ version|replace("-", "_") }}

source:
  fn: minqa_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/minqa_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/minqa/minqa_{{ version }}.tar.gz
  sha256: cfa193a4a9c55cb08f3faf4ab09c11b70412523767f19894e4eafc6e94cccd0c

build:
  merge_build_host: True  # [win]
  number: 1004
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{ compiler('fortran') }}  # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('m2w64_cxx') }}        # [win]
    - {{ compiler('m2w64_fortran') }}        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-rcpp >=0.9.10
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-rcpp >=0.9.10

test:
  commands:
    - $R -e "library('minqa')"           # [not win]
    - "\"%R%\" -e \"library('minqa')\""  # [win]

about:
  home: http://optimizer.r-forge.r-project.org
  license: GPL-2
  summary: Derivative-free optimization by quadratic approximation based on an interface to Fortran
    implementations by M. J. D. Powell.
  license_family: GPL2
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
