{% set version = "0.2.0" %}

package:
  name: pycox
  version: {{ version }}

source:
  git_url: https://github.com/havakv/pycox.git
  git_tag: v{{ version }}
  patches:
    - 0001-ensure-test-tensor-on-CPU-before-converting-to-numpy.patch

requirements:
  host:
    - python
    - torchtuples >=0.2.0
    - feather-format >=0.4.0
    - h5py >=2.8.0
    - numba >=0.44
    - scikit-learn >=0.21.2
    - requests >=2.22.0
  run:
    - python
    - torchtuples >=0.2.0
    - feather-format >=0.4.0
    - h5py >=2.8.0
    - numba >=0.44
    - scikit-learn >=0.21.2
    - requests >=2.22.0
    - pytorch >=1.2.0

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} setup.py install --single-version-externally-managed --record=record.txt

test:
  source_files:
    - tests
  requires:
    - pytest
    - lifelines # used by a few unit tests
  imports:
    - pycox
  commands:
    - pytest -v --tb=native tests

about:
  home: https://github.com/havakv/pycox.git
  license: BSD 2-clause
  license_family: BSD
  license_file: LICENSE
  summary: pycox is a python package for survival analysis and time-to-event prediction with PyTorch
