{% set name = "shap" %}
{% set version = "0.32.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/slundberg/{{ name }}/archive/{{ version }}.tar.gz
  sha256: ce6e70ba3c6b0af250463044aa07fde61bfe29e466bb9679bfd1da49550dddf7 

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - {{ compiler('cxx') }}
    - make
  host:
    - python
    - pip
    - setuptools
    - numpy
  run:
    - python
    - pandas
    - numpy
    - scikit-learn
    - scikit-image
    - scipy
    - matplotlib
    - tqdm
    - ipython
test:
  imports:
    - shap 

about:
  home: https://github.com/slundberg/shap 
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'A unified approach to explain the output of any machine learning model.'
  description: |
    SHAP (SHapley Additive exPlanations) is a unified approach to explain the output
    of any machine learning model. SHAP connects game theory with local explanations,
    uniting several previous methods and representing the only possible consistent
    and locally accurate additive feature attribution method based on expectations.
  doc_url: https://shap.readthedocs.io/en/latest/
  dev_url: https://github.com/slundberg/shap
