package:
  name: libxt-devel-cos7-ppc64le
  version: 1.1.5

source:
  - url: http://mirror.centos.org/altarch/7.6.1810/os/ppc64le/Packages/libXt-devel-1.1.5-3.el7.ppc64le.rpm
    sha256: 823b99d22ff9ce483f8f2ea9a4f8435547b52e06037b85aaf1a0e2902fde9a87
    folder: binary

build:
  number: 0
  noarch: generic
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - libxt-cos7-ppc64le ==1.1.5
  run:
    - libxt-cos7-ppc64le ==1.1.5

test:
  commands:
    - test -d "${PREFIX}/ppc64le-conda_cos7-linux-gnu/sysroot"
  requires:
    - zlib

about:
  home:
  license: LGPLv2/GPLv2
  license_family: GPL2
  summary:
  description: |

