{% set version = "0.2.0" %}

package:
  name: torchtuples
  version: {{ version }}

source:
  git_url: https://github.com/havakv/torchtuples.git
  git_tag: v{{ version }}
  patches:
    - 0001-relax-tolerance-for-one-testcase.patch

requirements:
  host:
    - python
    - numpy >=1.15.4
    - pandas >=0.24.2
    - matplotlib >=3.0.3
  run:
    - python
    - numpy >=1.15.4
    - pandas >=0.24.2
    - matplotlib >=3.0.3
    - pytorch >=1.2.0

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} setup.py install --single-version-externally-managed --record=record.txt

test:
  source_files:
    - tests
  requires:
    - pytest
  imports:
    - torchtuples
  commands:
    - pytest -v --tb=native tests

about:
  home: https://github.com/havakv/torchtuples.git
  license: BSD 2-clause
  license_family: BSD
  license_file: LICENSE
  summary: torchtuples is a small python package for training PyTorch models
