package:
  name: libice-devel-cos7-ppc64le
  version: 1.0.9

source:
  - folder: binary
    sha256: 6e623317f8ca06df5724db8d1cc7f18a95f695cdd9a5d12e4861e002e8411ee6
    url: http://mirror.centos.org/altarch/7/os/ppc64le/Packages/libICE-devel-1.0.9-9.el7.ppc64le.rpm
  - folder: source
    url: http://vault.centos.org/7.6.1810/os/Source/SPackages/libICE-1.0.9-9.el7.src.rpm

build:
  number: 0
  noarch: generic
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - libice-cos7-ppc64le ==1.0.9
  run:
    - libice-cos7-ppc64le ==1.0.9
about:
  description: 'The X.Org X11 ICE (Inter-Client Exchange) development package.'
  home: http://www.x.org
  license: MIT
  license_family: MIT
  summary: (CDT) X.Org X11 ICE development package
extra:
  copy_test_source_files: true
  final: true
