{% set version = '0.2.0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-vctrs
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/vctrs_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/vctrs/vctrs_{{ version }}.tar.gz
  sha256: 5bce8f228182ecaa51230d00ad8a018de9cf2579703e82244e0931fe31f20016

build:
  merge_build_host: True  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-backports
    - r-digest
    - r-ellipsis >=0.2.0
    - r-glue
    - r-rlang >=0.4.0
    - r-zeallot
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-backports
    - r-digest
    - r-ellipsis >=0.2.0
    - r-glue
    - r-rlang >=0.4.0
    - r-zeallot

test:
  commands:
    - $R -e "library('vctrs')"           # [not win]
    - "\"%R%\" -e \"library('vctrs')\""  # [win]

about:
  home: https://github.com/r-lib/vctrs
  license: GPL-3
  summary: Defines new notions of prototype and size that are used to provide tools for consistent
    and well-founded type-coercion and size-recycling, and are in turn connected to
    ideas of type- and size-stability useful for analyzing function interfaces.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - philip-khor

# Package: vctrs
# Title: Vector Helpers
# Version: 0.2.0
# Authors@R:  c(person(given = "Hadley", family = "Wickham", role = c("aut", "cre"), email = "hadley@rstudio.com"), person(given = "Lionel", family = "Henry", role = "aut", email = "lionel@rstudio.com"), person(given = "Davis", family = "Vaughan", role = "aut", email = "davis@rstudio.com"), person(given = "RStudio", role = "cph"))
# Description: Defines new notions of prototype and size that are used to provide tools for consistent and well-founded type-coercion and size-recycling, and are in turn connected to ideas of type- and size-stability useful for analyzing function interfaces.
# License: GPL-3
# URL: https://github.com/r-lib/vctrs
# BugReports: https://github.com/r-lib/vctrs/issues
# Depends: R (>= 3.2)
# Imports: backports, ellipsis (>= 0.2.0), digest, glue, rlang (>= 0.4.0), zeallot
# Suggests: bit64, covr, crayon, generics, knitr, pillar (>= 1.4.1), pkgdown, rmarkdown, testthat, tibble
# VignetteBuilder: knitr
# Encoding: UTF-8
# Language: en-GB
# LazyData: true
# RoxygenNote: 6.1.1
# NeedsCompilation: yes
# Packaged: 2019-07-02 19:29:52 UTC; lionel
# Author: Hadley Wickham [aut, cre], Lionel Henry [aut], Davis Vaughan [aut], RStudio [cph]
# Maintainer: Hadley Wickham <hadley@rstudio.com>
# Repository: CRAN
# Date/Publication: 2019-07-05 23:00:04 UTC
