#!/usr/bin/env python
# IBM_PROLOG_BEGIN_TAG
# 
# Copyright 2003,2016 IBM International Business Machines Corp.
# 
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
# 
#           http://www.apache.org/licenses/LICENSE-2.0
# 
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
#  implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
# 
#  IBM_PROLOG_END_TAG

# Script to create a dataset

from __future__ import print_function
import sys
import logging
import json
import vapi_core as vapi


def createDataset(jsonStr):
    dataset = None
    
    headers = {'Content-type': 'application/json'}
    url = vapi.cfg["baseUrl"] + "/datasets"
    logging.debug("url={}, json={}".format(url, jsonStr))
    
    rsp = vapi.post(url, headers=headers, data=jsonStr)

    if vapi.rspOk(rsp):
        dataset = rsp.json()
    else:
        logging.error("Failed to create dataset; {}".format(rsp.status_code))

    return dataset


if __name__ == '__main__':
    if len(sys.argv) != 2:
        vapi.eprint("ERR: You must provide the dataset json string")
        exit(1)
    if vapi.loadCfgInfo() == 0:
        dataset = createDataset(sys.argv[1])
        if dataset is not None:
            print(json.dumps(dataset, indent=2))
    else:
        vapi.eprint("ERR: Failed to load cfgInfo");

