#!/usr/bin/env python
# IBM_PROLOG_BEGIN_TAG
# 
# Copyright 2003,2016 IBM International Business Machines Corp.
# 
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
# 
#           http://www.apache.org/licenses/LICENSE-2.0
# 
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
#  implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
# 
#  IBM_PROLOG_END_TAG

# script to change/set the category with which a file is associated

from __future__ import print_function
import sys
import logging
import json
import vapi_core as vapi


def createTag(dsId, tagname):
    dataset = None

    headers = {"Content-type": "application/json"}
    body = {"name": tagname}
    url = vapi.cfg["baseUrl"] + "/datasets/" + dsId + "/tags";
    logging.info("URL: {}".format(url));
    
    rsp = vapi.post(url, headers=headers, data=json.dumps(body))
    if vapi.rspOk(rsp):
        print(json.dumps(rsp.json(), indent=2))


if __name__ == '__main__':
    if len(sys.argv) == 3:
        if vapi.loadCfgInfo() == 0:
            createTag(sys.argv[1], sys.argv[2])
        else:
            vapi.eprint("ERR: could not read cfg info")
            exit(2)
    else:
        vapi.eprint("ERR: You must specify a dataset id, tag name")
        vapi.eprint("Usage: createTag <dsId> <tagName>");
        exit(1)

