#!/usr/bin/env python
# IBM_PROLOG_BEGIN_TAG
# 
# Copyright 2003,2016 IBM International Business Machines Corp.
# 
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
# 
#           http://www.apache.org/licenses/LICENSE-2.0
# 
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
#  implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
# 
#  IBM_PROLOG_END_TAG

# Script to create a category for the given fileset
#
# Usage: createCategory DsId "{categoryJsonStr}"
#

from __future__ import print_function
import sys
import logging
import json
import vapi_core as vapi                        


def createCategory(dsId, jsonStr):
    category = None
    
    headers = {'Content-type': 'application/json'}
    url = vapi.cfg["baseUrl"] + "/datasets/" + dsId + "/categories"
    logging.debug("url={}; json={}".format(url, jsonStr))
    
    rsp = vapi.post(url, headers=headers, data=jsonStr)

    if vapi.rspOk(rsp):
        category = rsp.json()
    else:
        vapi.eprint("Failed to create category; {}".format(rsp.status_code))

    return category


if __name__ == '__main__':
    if len(sys.argv) != 3:
        vapi.eprint("ERR: You must provide datasetId and the new category info in a json str");
        vapi.eprint("usage: createCategory <dsId> <JsonString>")
        exit(1)
    if vapi.loadCfgInfo() == 0:
        cat = createCategory(sys.argv[1], sys.argv[2])
        if cat is not None:
            print(json.dumps(cat, indent=2))
    else:
        exit(2)
