#!/usr/bin/env python
# IBM_PROLOG_BEGIN_TAG
# 
# Copyright 2003,2016 IBM International Business Machines Corp.
# 
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
# 
#           http://www.apache.org/licenses/LICENSE-2.0
# 
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
#  implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
# 
#  IBM_PROLOG_END_TAG

# Script to delete a group of trained models

from __future__ import print_function
import sys
import logging
import json
import vapi_core as vapi


def deleteTrainedModels(modelList):

    headers = {'Content-type': 'application/json'}
    url = vapi.cfg["baseUrl"] + "/trained-models/action"
    req = {"action": "delete", "model_list": modelList}
    logging.debug("URL: {}".format(url));
    logging.debug("requestData: {}".format(json.dumps(req)));
    rsp = vapi.post(url, headers=headers, data=json.dumps(req))

    if not vapi.rspOk(rsp):
        vapi.eprint("ERR: Failed to delete trained models!")
    print(json.dumps(rsp.json(), indent=2))


if __name__ == '__main__':
    if len(sys.argv) == 2:
        if vapi.loadCfgInfo() == 0:
            deleteTrainedModels(json.loads(sys.argv[1]))
        else:
            exit(2)
    else:
        vapi.eprint("ERR: you must provide json list of model Ids (e.g. '[\"id1\",\"id2\"]')")
        exit(1)
               

