#!/usr/bin/env python
# IBM_PROLOG_BEGIN_TAG
# 
# Copyright 2003,2016 IBM International Business Machines Corp.
# 
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
# 
#           http://www.apache.org/licenses/LICENSE-2.0
# 
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
#  implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
# 
#  IBM_PROLOG_END_TAG

# Script to delete a task


from __future__ import print_function
import sys
import logging
import json
import vapi_core as vapi


def deleteDeployedTask(deploy_id):
    url = vapi.cfg["baseUrl"] + "/webapis/" +  deploy_id
    logging.debug("@@@ URL: {}".format(url));
    rsp = vapi.delete(url)

    if not vapi.rspOk(rsp):
        vapi.eprint("ERR: Failed to delete deployed task!")

    logging.info(json.dumps(rsp.json(), indent=2))


if __name__ == '__main__':
    if len(sys.argv) == 2:
        if vapi.loadCfgInfo() == 0:
            deleteDeployedTask(sys.argv[1])
        else:
            exit(2)
    else:
        vapi.eprint("Usage: {} <taskId>".format(sys.argv[0]))
        exit(1)
               

