#!/usr/bin/env python
# IBM_PROLOG_BEGIN_TAG
# 
# Copyright 2003,2016 IBM International Business Machines Corp.
# 
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
# 
#           http://www.apache.org/licenses/LICENSE-2.0
# 
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
#  implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
# 
#  IBM_PROLOG_END_TAG
# BEGIN
# END

# Script to get list of datasets 

from __future__ import print_function
import sys
import os
import os.path
import json
import logging

import requests
import vapi_core as vapi


def getDatasetList():
    ds_list = None

    url = vapi.cfg["baseUrl"] + "/datasets"
    logging.info("URL: {}".format(url));
    rsp = vapi.get(url)
    if (vapi.rspOk(rsp)):
        ds_list = rsp.json()

    return ds_list



if (__name__ == '__main__'):
    if (vapi.loadCfgInfo() == 0):
        dslist = getDatasetList()
        if dslist != None:
         print(json.dumps(dslist, indent=2))           
    else:
        exit(1)

