#!/usr/bin/env python
# IBM_PROLOG_BEGIN_TAG
# 
# Copyright 2003,2016 IBM International Business Machines Corp.
# 
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
# 
#           http://www.apache.org/licenses/LICENSE-2.0
# 
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
#  implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
# 
#  IBM_PROLOG_END_TAG

# Script to get a specific task 

from __future__ import print_function
import sys
import os
import os.path
import logging
import json

import vapi_core as vapi


def getDLTask(task_id):
    task = None

    url = vapi.cfg["baseUrl"] + "/dltasks/" + task_id
    logging.info("getDLTask URL= {}".format(url));
    rsp = vapi.get(url)
    if (vapi.rspOk(rsp)):
        task = rsp.json()
    return task


if __name__ == '__main__':
    if len(sys.argv) == 2:
        if vapi.loadCfgInfo() == 0:
            task = getDLTask(sys.argv[1])
            if task is not None:
                print(json.dumps(task, indent=2))
        else:
            exit(2)
    else:
        vapi.eprint("ERR: You must specify a task id")
        exit(1)

