#!/usr/bin/env python
# IBM_PROLOG_BEGIN_TAG
# 
# Copyright 2003,2016 IBM International Business Machines Corp.
# 
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
# 
#           http://www.apache.org/licenses/LICENSE-2.0
# 
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
#  implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
# 
#  IBM_PROLOG_END_TAG

# Script to get an authentication toke for vision

from __future__ import print_function
import sys
import os
import os.path
import logging
import json

import requests
import vapi_core as vapi


                        
def getVisionToken(userName, password):
    accessToken = None

    headers = {'Content-type': 'application/json'}

    jsonStr = {
               'grant_type':'password',
               'username':'%s' % userName,
               'password':'%s' % password,
              }

    url = vapi.cfg["baseUrl"] + "/tokens"
    logging.debug("url={}".format(url))
    logging.debug("headers={}".format(headers))
    logging.debug("data={}".format(jsonStr))
    
    rsp = vapi.post(url, headers=headers, data=json.dumps(jsonStr))

    if (vapi.rspOk(rsp)):
        accessToken = rsp.json()
    else:
        logging.error("Failed to getToken; {}".format(rsp.status_code))

    return accessToken 


if (__name__ == '__main__'):
    if (len(sys.argv) != 3):
        vapi.eprint("ERR: You must provide the username and password")
        exit(1)
    if (vapi.loadCfgInfo() == 0):
        token = getVisionToken(sys.argv[1], sys.argv[2])
        if token != None:
            print(json.dumps(token))
    else:
        vapi.eprint("ERR: Failed to load cfgInfo");

