#!/usr/bin/env python
# IBM_PROLOG_BEGIN_TAG
# 
# Copyright 2003,2016 IBM International Business Machines Corp.
# 
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
# 
#           http://www.apache.org/licenses/LICENSE-2.0
# 
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
#  implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
# 
#  IBM_PROLOG_END_TAG

# Script to create a dataset

from __future__ import print_function
import sys
import os
import os.path
import logging
import json

import requests
import vapi_core as vapi


                        
def renameDataset(dsId, newName):
    dataset = None
    msg = {
        "data" : newName,
        "action" : "rename"
    }

    headers = {'Content-type': 'application/json'}
    url = vapi.cfg["baseUrl"] + "/datasets/" + dsId + "/action"
    logging.info("renameDataset: url={}, json={}".format(url, msg))

    rsp = vapi.post(url, data=json.dumps(msg))

    if (vapi.rspOk(rsp)):
        dataset = rsp.json()
    else:
        vapi.eprint("ERR: Failed to update dataset; {}".format(rsp.status_code))

    return dataset


if (__name__ == '__main__'):
    if (len(sys.argv) != 3):
        vapi.eprint("ERR: You must provide the new name for the dataset")
        exit(1)
    if (vapi.loadCfgInfo() == 0):
        dataset = renameDataset(sys.argv[1], sys.argv[2])
        if dataset != None:
            print(json.dumps(dataset, indent=2))
    else:
        vapi.eprint("ERR: Failed to load cfgInfo");

