package:
  name: libsm-devel-cos7-ppc64le
  version: 1.2.2

source:
  - folder: binary
    sha256: 0967d96cd46a7c47788fd2986dcb234e9fe1dfa21dc81bb44069c33c3cdbce60
    url: http://mirror.centos.org/altarch/7/os/ppc64le/Packages/libSM-devel-1.2.2-2.el7.ppc64le.rpm
  - folder: source
    url: http://vault.centos.org/7.6.1810/os/Source/SPackages/libSM-1.2.2-2.el7.src.rpm

build:
  number: 0
  noarch: generic
  missing_dso_whitelist:
    - '*'
requirements:
  build:
    - libsm-cos7-ppc64le ==1.2.2
  run:
    - libsm-cos7-ppc64le ==1.2.2
about:
  description: 'The X.Org X11 SM (Session Management) development package'
  home: http://www.x.org
  license: MIT
  license_family: MIT
  summary: (CD) X.Org X11 SM development package
extra:
  copy_test_source_files: true
  final: true
