{% set version = '1.3.3' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-mscmt
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/MSCMT_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/MSCMT/MSCMT_{{ version }}.tar.gz
  sha256: 43cddbc9aa13bbb330b99512ed549a165fd1ac1c747da8d7bcc8b3720da3c2a4

build:
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('fortran') }}        # [not win]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-rdpack
    - r-rglpk
    - r-ggplot2
    - r-lpsolve
    - r-lpsolveapi
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-rdpack
    - r-rglpk
    - r-ggplot2
    - r-lpsolve
    - r-lpsolveapi

test:
  commands:
    - $R -e "library('MSCMT')"           # [not win]
    - "\"%R%\" -e \"library('MSCMT')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=MSCMT
  license: GPL
  summary: "Three generalizations of the synthetic control method (which has  already an implementation
    in package 'Synth') are implemented: first,  'MSCMT' allows for using multiple outcome
    variables, second, time series  can be supplied as economic predictors, and third,
    a well-defined  cross-validation approach can be used. Much effort has been taken
    to make the implementation as stable as possible  (including edge cases) without
    losing computational efficiency. A detailed description of the main algorithms is
    given in  Becker and Kl\xF6\xDFner (2018) <doi:10.1016/j.ecosta.2017.08.002>."
  license_family: GPL
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - jayfurmanek

# Package: MSCMT
# Type: Package
# Encoding: UTF-8
# Version: 1.3.3
# Date: 2018-05-04
# Title: Multivariate Synthetic Control Method Using Time Series
# Authors@R: c(person("Martin","Becker", role = c("aut","cre"), email = "martin.becker@mx.uni-saarland.de", comment=c(ORCID="0000-0003-2336-9751")), person("Stefan","Kloner", role = c("aut"), email = "S.Kloessner@mx.uni-saarland.de"), person("Karline","Soetaert", role = c("com"), email = "karline.soetaert@nioz.nl"), person("LAPACK authors", role = "cph"))
# Depends: R (>= 3.2.0)
# Imports: stats, utils, parallel, lpSolve, ggplot2, lpSolveAPI, Rglpk, Rdpack
# Suggests: Synth, DEoptim, rgenoud, DEoptimR, GenSA, GA, soma, cmaes, Rmalschains, NMOF, nloptr, hydroPSO, pso, LowRankQP, kernlab, reshape, knitr, rmarkdown
# Description: Three generalizations of the synthetic control method (which has  already an implementation in package 'Synth') are implemented: first,  'MSCMT' allows for using multiple outcome variables, second, time series  can be supplied as economic predictors, and third, a well-defined  cross-validation approach can be used. Much effort has been taken to make the implementation as stable as possible  (including edge cases) without losing computational efficiency. A detailed description of the main algorithms is given in  Becker and Kloner (2018) <doi:10.1016/j.ecosta.2017.08.002>.
# License: GPL
# Copyright: inst/COPYRIGHTS
# LazyData: yes
# RoxygenNote: 6.0.1
# VignetteBuilder: knitr
# BuildVignettes: yes
# NeedsCompilation: yes
# Packaged: 2018-05-04 06:54:15 UTC; mabe003
# Author: Martin Becker [aut, cre] (<https://orcid.org/0000-0003-2336-9751>), Stefan Kloner [aut], Karline Soetaert [com], LAPACK authors [cph]
# Maintainer: Martin Becker <martin.becker@mx.uni-saarland.de>
# Repository: CRAN
# Date/Publication: 2018-05-04 07:53:28 UTC
