{% set version="3.0" %}
{% set sha256="f0e8bb1f9b7eb0b01285495a2699df3a4b766784c1765a8f1aeedf63c0806369" %}

package:
  name: zip
  version: {{ version }}

source:
  url: ftp://ftp.info-zip.org/pub/infozip/src/zip{{ version.replace(".", "") }}.tgz
  sha256: {{ sha256 }}
  patches:
    0001-use-CC-env-variable-for-build.patch

build:
  number: 0
  skip: True  # [win]
  script: make -f unix/Makefile generic && mkdir -p $PREFIX/bin && mv zip $PREFIX/bin/

requirements:
  build:
    - {{ compiler('c') }}
    - make
    - patch

test:
  commands:
    - zip -h

about:
  home: http://www.info-zip.org/
  license: BSD-like
  license_file: LICENSE
  summary: simple program for unzipping files

extra:
  recipe-maintainers:
    - msarahan
    - jerowe
