{% set name = "xport" %}
{% set version = "2.0.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: "0afe035727d4464d748334dbc57c760a82d1493b8c117493738d8b4c2f4ddc65"

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
  run:
    - python

about:
  home: "https://github.com/selik/xport"
  license: "MIT"
  license_family: "MIT"
  license_file: ""
  summary: "SAS XPORT file reader"
  doc_url: ""
  dev_url: ""

extra:
  recipe-maintainers:
    - jayfurmanek
