{% set java_version = "1.8.0" %}
{% set sha256sum = "15866faa8793e0af88c9bce2ab40189161b07541958221869e3ab3cfd23e8804" %}
{% set pkg_version = "1.8.0.181-7.b13.el7" %}

package:
  name: java-{{ java_version }}-openjdk-headless-ppcl64le
  version: {{ java_version }}.181

source:
  - url: http://mirror.centos.org/altarch/7/os/ppc64le/Packages/java-{{ java_version }}-openjdk-headless-{{ pkg_version }}.ppc64le.rpm
    sha256: {{ sha256sum }}
    folder: binary
  - url: http://mirror.centos.org/altarch/7/os/ppc64le/Packages/tzdata-java-2018e-3.el7.noarch.rpm
    folder: tzdata


build:
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - chkconfig-cos7-ppc64le >=1.7
    - chkconfig-cos7-ppc64le >=1.7
    - copy-jdk-configs-cos7-ppc64le >=2.2
    - javapackages-tools-cos7-ppc64le >=3.4.1
    - libjpeg-turbo-cos7-ppc64le ==1.2.90
    - nss-cos7-ppc64le >=3.28.4
    - nss-softokn-cos7-ppc64le >=3.28.3
test:
   files:
    - existence_test
   commands:
    - bash existence_test {{ pkg_version }}


outputs:
  - name: java-1.8.0-openjdk-headless-ppcl64le
    requirements:
      run:
        - chkconfig-cos7-ppc64le >=1.7
        - chkconfig-cos7-ppc64le >=1.7
        - copy-jdk-configs-cos7-ppc64le >=2.2
        - javapackages-tools-cos7-ppc64le >=3.4.1
        - libjpeg-turbo-cos7-ppc64le ==1.2.90
        - nss-cos7-ppc64le >=3.28.4
        - nss-softokn-cos7-ppc64le >=3.28.3

    about:
      home: http://openjdk.java.net/
      license: ASL 1.1 and ASL 2.0 and GPL+ and GPLv2 and GPLv2 with exceptions and LGPL+ and LGPLv2 and MPLv1.0 and MPLv1.1 and Public Domain and W3C
      license_family: GPL2
      summary: "(CDT) The OpenJDK runtime environment without audio and video support"
      description: |
        The OpenJDK runtime environment without audio and video
