{% set version = '2.0.13' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-microsynth
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/microsynth_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/microsynth/microsynth_{{ version }}.tar.gz
  sha256: 4f11f615028386457c55b40dd02277cd8440ce4df4aff639a80701dad73c5bc6

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-lowrankqp
    - r-mass
    - r-boot
    - r-kernlab
    - r-nleqslv
    - r-pracma
    - r-survey
  run:
    - r-base
    - r-lowrankqp
    - r-mass
    - r-boot
    - r-kernlab
    - r-nleqslv
    - r-pracma
    - r-survey

test:
  commands:
    - $R -e "library('microsynth')"           # [not win]
    - "\"%R%\" -e \"library('microsynth')\""  # [win]

about:
  home: https://github.com/ssdavenport/microsynth
  license: GPL-3
  summary: A generalization of the 'Synth' package that is designed for data at a more granular
    level (e.g., micro-level). Provides functions to construct weights (including propensity
    score-type weights) and run analyses for synthetic control methods with micro- and
    meso-level data; see Robbins, Saunders, and Kilmer  (2017) <doi:10.1080/01621459.2016.1213634>.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - jayfurmanek

# Package: microsynth
# Title: Synthetic Control Methods with Micro- And Meso-Level Data
# Version: 2.0.13
# Description: A generalization of the 'Synth' package that is designed for data at a more granular level (e.g., micro-level). Provides functions to construct weights (including propensity score-type weights) and run analyses for synthetic control methods with micro- and meso-level data; see Robbins, Saunders, and Kilmer  (2017) <doi:10.1080/01621459.2016.1213634>.
# Depends: R (>= 3.3.0)
# License: GPL-3
# Encoding: UTF-8
# LazyData: true
# Imports: boot, survey, MASS, stats, utils, kernlab, LowRankQP, nleqslv, pracma, parallel
# Suggests: knitr, xlsx, rmarkdown
# RoxygenNote: 6.1.1
# Authors@R: c( person("Michael", "Robbins", , "mrobbins@rand.org", c("aut", "cre")), person("Steven", "Davenport", , "sdavenpo@rand.org", "aut"))
# VignetteBuilder: knitr
# NeedsCompilation: no
# Author: Michael Robbins [aut, cre], Steven Davenport [aut]
# Maintainer: Michael Robbins <mrobbins@rand.org>
# URL: https://github.com/ssdavenport/microsynth
# Packaged: 2019-04-10 20:36:09 UTC; sdavenpo
# Repository: CRAN
# Date/Publication: 2019-04-10 21:04:21 UTC
