{% set version = '0.4.2' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-bibtex
  version: {{ version|replace("-", "_") }}

source:
  fn: bibtex_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/bibtex_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/bibtex/bibtex_{{ version }}.tar.gz
  sha256: 1f06ab3660c940405230ad16ff6e4ba38d4418a59cd9b16d78a4349f8b488372

build:
  merge_build_host: True  # [win]
  number: 1003
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-stringr
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-stringr

test:
  commands:
    - $R -e "library('bibtex')"           # [not win]
    - "\"%R%\" -e \"library('bibtex')\""  # [win]

about:
  home: https://github.com/romainfrancois/bibtex
  license: GPL (>= 2)
  summary: 'Utility to parse a bibtex file. '
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - tfenne
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
